apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: billing-service
data:
  AWS_REGION: "us-east-1"
  ESTIMATES_TABLE: "estimates"
  PAYMENTS_TABLE: "payments"
  GIN_MODE: "release"
