apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: billing-service-hpa
  namespace: billing-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: billing-service-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
