apiVersion: v1
kind: Secret
metadata:
  name: newrelic-license-key
  namespace: newrelic
type: Opaque
stringData:
  # Substitua YOUR_LICENSE_KEY_HERE pela sua license key do New Relic
  # Obtenha em: https://one.newrelic.com/admin-portal/api-keys/home
  license: "a642c3dd964def913073610eac2c7889FFFFNRAL"
