apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: newrelic-infra
  namespace: newrelic
  labels:
    app: newrelic-infra
    app.kubernetes.io/name: newrelic-infrastructure
spec:
  selector:
    matchLabels:
      app: newrelic-infra
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: newrelic-infra
        app.kubernetes.io/name: newrelic-infrastructure
    spec:
      serviceAccountName: newrelic
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: newrelic-infra
          image: newrelic/infrastructure-k8s:2.13.15
          securityContext:
            privileged: true
          env:
            - name: NRIA_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic-license-key
                  key: license
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: newrelic-config
                  key: cluster-name
            - name: NRIA_VERBOSE
              value: "0"
            - name: NRIA_CUSTOM_ATTRIBUTES
              value: '{"environment":"production","team":"mecanica-xpto"}'
            - name: NRIA_PASSTHROUGH_ENVIRONMENT
              value: "KUBERNETES_SERVICE_HOST,KUBERNETES_SERVICE_PORT,CLUSTER_NAME,CADVISOR_PORT,NRK8S_NODE_NAME,KUBE_STATE_METRICS_URL,KUBE_STATE_METRICS_POD_LABEL,TIMEOUT,ETCD_TLS_SECRET_NAME,ETCD_TLS_SECRET_NAMESPACE,API_SERVER_SECURE_PORT,KUBE_STATE_METRICS_SCHEME,KUBE_STATE_METRICS_PORT,SCHEDULER_ENDPOINT_URL,ETCD_ENDPOINT_URL,CONTROLLER_MANAGER_ENDPOINT_URL,API_SERVER_ENDPOINT_URL,DISABLE_KUBE_STATE_METRICS,DISCOVERY_CACHE_TTL"
            - name: NRK8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NRIA_DISPLAY_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NRIA_ENABLE_PROCESS_METRICS
              value: "true"
          volumeMounts:
            - name: host-volume
              mountPath: /host
              readOnly: true
            - name: host-var-cache
              mountPath: /var/cache
            - name: host-run
              mountPath: /var/run/docker.sock
            - name: host-log
              mountPath: /var/log
              readOnly: true
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 150Mi
      volumes:
        - name: host-volume
          hostPath:
            path: /
        - name: host-var-cache
          hostPath:
            path: /var/cache
        - name: host-run
          hostPath:
            path: /var/run/docker.sock
        - name: host-log
          hostPath:
            path: /var/log
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
