apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: billing-service
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "local"
  AWS_SECRET_ACCESS_KEY: "local"
  MERCADOPAGO_ACCESS_TOKEN: ""
