apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: billing-service
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
  MERCADOPAGO_ACCESS_TOKEN: "YOUR_MERCADOPAGO_ACCESS_TOKEN"
